<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class ContractUserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $contract_user = array(
            array('contract_id' => '22','user_id' => '1'),
            array('contract_id' => '21','user_id' => '1'),
            array('contract_id' => '19','user_id' => '1'),
            array('contract_id' => '13','user_id' => '1'),
            array('contract_id' => '9','user_id' => '1'),
            array('contract_id' => '8','user_id' => '1'),
            array('contract_id' => '7','user_id' => '1'),
            array('contract_id' => '6','user_id' => '1'),
            array('contract_id' => '5','user_id' => '1'),
            array('contract_id' => '4','user_id' => '1'),
            array('contract_id' => '3','user_id' => '1'),
            array('contract_id' => '2','user_id' => '1'),
            array('contract_id' => '18','user_id' => '1'),
            array('contract_id' => '17','user_id' => '1'),
            array('contract_id' => '20','user_id' => '1'),
            array('contract_id' => '10','user_id' => '1'),
            array('contract_id' => '11','user_id' => '1'),
            array('contract_id' => '16','user_id' => '1'),
            array('contract_id' => '1','user_id' => '1'),
            array('contract_id' => '14','user_id' => '1'),
            array('contract_id' => '15','user_id' => '1'),
            array('contract_id' => '12','user_id' => '1'),
            array('contract_id' => '22','user_id' => '2'),
            array('contract_id' => '21','user_id' => '2'),
            array('contract_id' => '19','user_id' => '2'),
            array('contract_id' => '13','user_id' => '2'),
            array('contract_id' => '9','user_id' => '2'),
            array('contract_id' => '8','user_id' => '2'),
            array('contract_id' => '7','user_id' => '2'),
            array('contract_id' => '6','user_id' => '2'),
            array('contract_id' => '5','user_id' => '2'),
            array('contract_id' => '4','user_id' => '2'),
            array('contract_id' => '3','user_id' => '2'),
            array('contract_id' => '2','user_id' => '2'),
            array('contract_id' => '18','user_id' => '2'),
            array('contract_id' => '17','user_id' => '2'),
            array('contract_id' => '20','user_id' => '2'),
            array('contract_id' => '10','user_id' => '2'),
            array('contract_id' => '11','user_id' => '2'),
            array('contract_id' => '16','user_id' => '2'),
            array('contract_id' => '1','user_id' => '2'),
            array('contract_id' => '14','user_id' => '2'),
            array('contract_id' => '15','user_id' => '2'),
            array('contract_id' => '12','user_id' => '2'),
            array('contract_id' => '22','user_id' => '25'),
            array('contract_id' => '21','user_id' => '25'),
            array('contract_id' => '19','user_id' => '25'),
            array('contract_id' => '13','user_id' => '25'),
            array('contract_id' => '9','user_id' => '25'),
            array('contract_id' => '8','user_id' => '25'),
            array('contract_id' => '7','user_id' => '25'),
            array('contract_id' => '6','user_id' => '25'),
            array('contract_id' => '5','user_id' => '25'),
            array('contract_id' => '4','user_id' => '25'),
            array('contract_id' => '3','user_id' => '25'),
            array('contract_id' => '2','user_id' => '25'),
            array('contract_id' => '18','user_id' => '25'),
            array('contract_id' => '17','user_id' => '25'),
            array('contract_id' => '20','user_id' => '25'),
            array('contract_id' => '10','user_id' => '25'),
            array('contract_id' => '11','user_id' => '25'),
            array('contract_id' => '16','user_id' => '25'),
            array('contract_id' => '1','user_id' => '25'),
            array('contract_id' => '14','user_id' => '25'),
            array('contract_id' => '15','user_id' => '25'),
            array('contract_id' => '12','user_id' => '25'),
            array('contract_id' => '9','user_id' => '26'),
            array('contract_id' => '9','user_id' => '27'),
            array('contract_id' => '6','user_id' => '28'),
            array('contract_id' => '9','user_id' => '28'),
            array('contract_id' => '9','user_id' => '29'),
            array('contract_id' => '9','user_id' => '31'),
            array('contract_id' => '6','user_id' => '32'),
            array('contract_id' => '15','user_id' => '33'),
            array('contract_id' => '14','user_id' => '33'),
            array('contract_id' => '9','user_id' => '34'),
            array('contract_id' => '7','user_id' => '35'),
            array('contract_id' => '6','user_id' => '36'),
            array('contract_id' => '7','user_id' => '37'),
            array('contract_id' => '7','user_id' => '38'),
            array('contract_id' => '6','user_id' => '39'),
            array('contract_id' => '7','user_id' => '40'),
            array('contract_id' => '7','user_id' => '41'),
            array('contract_id' => '3','user_id' => '42'),
            array('contract_id' => '3','user_id' => '43'),
            array('contract_id' => '3','user_id' => '44'),
            array('contract_id' => '3','user_id' => '45'),
            array('contract_id' => '3','user_id' => '46'),
            array('contract_id' => '3','user_id' => '47'),
            array('contract_id' => '9','user_id' => '48'),
            array('contract_id' => '14','user_id' => '49'),
            array('contract_id' => '3','user_id' => '24'),
            array('contract_id' => '6','user_id' => '24'),
            array('contract_id' => '7','user_id' => '24'),
            array('contract_id' => '9','user_id' => '24'),
            array('contract_id' => '7','user_id' => '50'),
            array('contract_id' => '10','user_id' => '36'),
            array('contract_id' => '10','user_id' => '24'),
            array('contract_id' => '9','user_id' => '51'),
            array('contract_id' => '10','user_id' => '26'),
            array('contract_id' => '9','user_id' => '30'),
            array('contract_id' => '10','user_id' => '35'),
            array('contract_id' => '10','user_id' => '42'),
            array('contract_id' => '10','user_id' => '51'),
            array('contract_id' => '10','user_id' => '50'),
            array('contract_id' => '10','user_id' => '48'),
            array('contract_id' => '10','user_id' => '47'),
            array('contract_id' => '10','user_id' => '46'),
            array('contract_id' => '10','user_id' => '45'),
            array('contract_id' => '10','user_id' => '44'),
            array('contract_id' => '10','user_id' => '43'),
            array('contract_id' => '10','user_id' => '41'),
            array('contract_id' => '10','user_id' => '40'),
            array('contract_id' => '10','user_id' => '39'),
            array('contract_id' => '10','user_id' => '38'),
            array('contract_id' => '10','user_id' => '37'),
            array('contract_id' => '10','user_id' => '34'),
            array('contract_id' => '10','user_id' => '33'),
            array('contract_id' => '10','user_id' => '32'),
            array('contract_id' => '10','user_id' => '31'),
            array('contract_id' => '10','user_id' => '30'),
            array('contract_id' => '10','user_id' => '27'),
            array('contract_id' => '10','user_id' => '28'),
            array('contract_id' => '10','user_id' => '29'),
            array('contract_id' => '1','user_id' => '37'),
            array('contract_id' => '21','user_id' => '37'),
            array('contract_id' => '22','user_id' => '37'),
            array('contract_id' => '1','user_id' => '30'),
            array('contract_id' => '22','user_id' => '30'),
            array('contract_id' => '21','user_id' => '30'),
            array('contract_id' => '6','user_id' => '52'),
            array('contract_id' => '10','user_id' => '52'),
            array('contract_id' => '3','user_id' => '53'),
            array('contract_id' => '10','user_id' => '53'),
            array('contract_id' => '3','user_id' => '54'),
            array('contract_id' => '10','user_id' => '54'),
            array('contract_id' => '3','user_id' => '55'),
            array('contract_id' => '10','user_id' => '55'),
            array('contract_id' => '23','user_id' => '2'),
            array('contract_id' => '23','user_id' => '1'),
            array('contract_id' => '15','user_id' => '28'),
            array('contract_id' => '9','user_id' => '33'),
            array('contract_id' => '15','user_id' => '37'),
            array('contract_id' => '14','user_id' => '37'),
            array('contract_id' => '6','user_id' => '56'),
            array('contract_id' => '10','user_id' => '56'),
            array('contract_id' => '24','user_id' => '2'),
            array('contract_id' => '7','user_id' => '57'),
            array('contract_id' => '10','user_id' => '57'),
            array('contract_id' => '7','user_id' => '58'),
            array('contract_id' => '10','user_id' => '58'),
            array('contract_id' => '6','user_id' => '59'),
            array('contract_id' => '10','user_id' => '59'),
            array('contract_id' => '3','user_id' => '60'),
            array('contract_id' => '21','user_id' => '42'),
            array('contract_id' => '22','user_id' => '42'),
            array('contract_id' => '14','user_id' => '42'),
            array('contract_id' => '3','user_id' => '61'),
            array('contract_id' => '10','user_id' => '61'),
            array('contract_id' => '6','user_id' => '62'),
            array('contract_id' => '10','user_id' => '62'),
            array('contract_id' => '13','user_id' => '49'),
            array('contract_id' => '15','user_id' => '30'),
            array('contract_id' => '14','user_id' => '30'),
            array('contract_id' => '21','user_id' => '57'),
            array('contract_id' => '22','user_id' => '57'),
            array('contract_id' => '3','user_id' => '63'),
            array('contract_id' => '13','user_id' => '63'),
            array('contract_id' => '3','user_id' => '64'),
            array('contract_id' => '13','user_id' => '64'),
            array('contract_id' => '6','user_id' => '65'),
            array('contract_id' => '16','user_id' => '37')
          );

          DB::table('contract_user')->insert($contract_user);
    }
}
